notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: u144kGcMmHrmtotCm5BRC02Gyc0RUNZJIkDpRLKvBnU5Y0SgAUH2MpQN3b2VCbHfljAIAWELnvH0C6QbYk8WwC0rmauEVe20ZwDWz8TYopP+0iz4hfhP/7BpU2dWLRMa/hYOqlESw7f1nvy2YQ4tCQO0UEMGfzUKPZMG5TotGWtRipBdbOsmSVDs7qNGNje0dtgB36ZVkU0f7RnkgsiJ8tG3sEhFY5tr73AFi1W6DU5u8yRiyFVMjibTwhQOsSmflZ5GdfBHW9As/DZdnyX7cIk73LKYGUzPDJ0PGEC5sDbeG6Zb1Of7HNBRkRjX1lX3C0R2nz0raDNpjk/vy5Jnk4sKxe3RPLc3Mh5RuJlPiy7uxdrJ3adg4m7rRr2OKRLX0i0TJVECqORaEyKSchW+KICVzHIZHhPg9qhHabelrXCTGQfKkbjX6UoJpXkTtNQ1JFawXH9ejkk8NTgqI1LRfiGmlQia4fhgCjwAFLsikRQq4Ijtun8jBoTdoTJdNABqeYt2X/3ZA8W3ACkJ1NirETw9HSiI10D2tK4e5aSahMaF8tcWVKiGuv6ZWzrAMGTwD13nya5BHZixOSX4zUxRogRPLkZHAoUlje6bftWdL4QmMZtcFDGHWKMDAZ0ZMfxIX5k7ZFGDnPcv7oOrZNbF2p+gP5au1xTDy9yFY/UYdI4=
  api_key:
  on:
    tags: true
