notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: UrH0MKd0uflwlEn8gVuqcpc2ayj3qP/W3/yyJfzpJpCyp2ON/bP7NC+CEPpZZ+LI5D1iWFSQ2T7YDMjHn9nxMwErHUPbrxKzWaA3evPy6Z5mVuBh5FmKEafEIzsMUwp2KHnAH1c3cg5+6cUFWZMmFC38jcQjuDb8hR1gWbK2E1IiCod8xlGfzqP+83pOmCTgdeyegIUpODFp7n0laBl4nRfI/9kFjaIpyvqVYGQj+Rg68WzEP//EYigaQEcnIQon8mBituc30N4H6zWvB0YUHiYch17uargBN/c5GgClSkSNwMxvg3wknJgmydAv+7sUlw0RW0XVob+sFnfstsQOqtHO5IpfC3c7KfXVWW8uW3EiruPAb8i9zlZao5e7DqogbIOM4HSlnnpJCGjkeRku8DAPZmQhHcRvEQolTclXQd8beXVew94NjIb6P5bXTLZR/R15VEGC6kkC/DSStLBsAuhYZuGvBsYVt/P9RNumCChPFz7thB5aNFrBbtQwQxzfSTedcQ0jHYj1jLZmMkuY21YFpyWrr5qhPGTT4MBD4EPRBaadhrwwB73E0oqzXNv+fCkGFDe5HApm5Z8r+lydcM3Xz5+7AFmjOEVGBilbYMLw1SDYOdRl0xV4e4q+GZiMSkvspXvInPeUb50EJolsdIKvGARsaved6L2yuiGPM8c=
  api_key:
    secure: rrepAcWYKkfKAiwDnToBUcYgdUGcAFvzhP6NuYUhbmboAtvaLK1vmcXdtT+UAv+JV2rRK3IcwfP5SPioq5PEuKeyXMnIOqUk/lYRPfQfmfuLY/hirerea+4o1ifHj1N5MFAS10xa69S93Bg4t+8YVlDqyiUzBATdIETP8sIR8v8Ap9y2SVrAv8pKz3WCZWikBOUpsEQ9ivrNlNwgbRyXourCp7vbdlf+gIIvhKr1rmKstug1YVB5BtfVyxyjtEhrm+HLcCj5pIDLx/CJuR10mxoJ8bcJyxgmuEm12jvmik+SFi/lhYQFIxoIwg0x5qf/k+oIP2dBOx5As8JPiG/ehiBOhJoMJLCtL7F69P2kq+RIl9fq1xFms7wNLJ48kbXkbcWO2tWbRrolurlZyXm+MjFt3XmGUEAN/++8hJ9U6rzuHm+1m2cwZ/5A8bgnG60BwmsKNSasrorbhPPgJQhQBY01ArlIsJasz8PmiLErpZ2Xv759nvKcK2SMnHeNqjNFtwaaTRBZmwquINc0NqQ6zss7WrNxY/eEPjBcd2Kab62NtwevSpvyY4g6Pk75Wh4R/zqCjpGWMEKLBH0VrsdsB44ojalx3vrrTJ0PcAp8HVXZsLN2xLi2JLZmyVowyGhSuKavhNUjbopc/7TzFzu16v63+WYwggmh37NbzFiprRE=
  on:
    tags: true
